import images from "./images";

const desserts = [
  {
    img: images.desert1,
    title: "Кекс",
    text: `Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...`,
    cost: 475,
    news: true,
    xit: false,
    new: true,
  },
  {
    img: images.desert2,
    title: "Булочки",
    text: `Сливочный сыр, семга татаки с тростниковым сахаром, соус у...`,
    cost: 395,
    news: true,
    xit: true,
    new: false,
  },
  {
    img: images.desert3,
    title: "Панки",
    text: `Действительно много семги, сливочный сыр, огурец, рис, н...`,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.desert4,
    title: "Мороженое",
    text: `Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...`,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.desert4,
    title: "Мороженое",
    text: `Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...`,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.desert5,
    title: "Мини",
    text: `Действительно много семги, сливочный сыр, огурец, рис, н...`,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.desert6,
    title: "Мороженое",
    text: `Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...`,
    cost: 475,
    news: false,
    xit: false,
    new: true,
  },
  {
    img: images.desert3,
    title: "Булочки",
    text: `Сливочный сыр, семга татаки с тростниковым сахаром, соус у...`,
    cost: 395,
    news: false,
    xit: true,
    new: false,
  },
];

export default desserts;
