import images from "./images";

const drinks = [
  {
    img: images.gamefuel,
    title: "Game Fuel",
    text: `Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...`,
    cost: 475,
    news: true,
    xit: false,
    new: true,
  },
  {
    img: images.blackpepsi,
    title: "Pepsi (без сахара)",
    text: `Сливочный сыр, семга татаки с тростниковым сахаром, соус у...`,
    cost: 395,
    news: true,
    xit: true,
    new: false,
  },
  {
    img: images.bluepepsi,
    title: "Pepsi",
    text: `Действительно много семги, сливочный сыр, огурец, рис, н...`,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.redpepsi,
    title: "Pepsi (Mild Cherry)",
    text: `Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...`,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.whitepepsi,
    title: "Pepsi (лёгкый вкус)",
    text: ``,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.mirinda,
    title: "Mirinda",
    text: ``,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.gamefuel,
    title: "Game Fuel",
    text: ``,
    cost: 475,
    news: false,
    xit: false,
    new: true,
  },
  {
    img: images.blackpepsi,
    title: "Pepsi",
    text: ``,
    cost: 395,
    news: false,
    xit: true,
    new: false,
  },
];

export default drinks;
