import images from "./images";

const pizza = [
  {
    img: images.chilipizza,
    title: "Чикен Сладкий Чили",
    text: `Курица, Лук, Перец Халапеньо, Сыр Моцарелла, Томатный соу...`,
    cost: 399,
    news: true,
    xit: false,
    new: true,
  },
  {
    img: images.pizzakolbas,
    title: "EASY PEASY огуречный расколбас",
    text: `Курица, Лук, Перец Халапеньо...`,
    cost: 549,
    news: true,
    xit: true,
    new: false,
  },
  {
    img: images.chickenpizza,
    title: "EASY PEASY чикен а-ля хрен",
    text: `Курица, Лук, Соус Карбонара,...`,
    cost: 249,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.sezonpizza,
    title: "4 сезона",
    text: `Бекон, Ветчина, Грибы, Курица, Лук, Маслины, Огурцы мари...`,
    cost: 630,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.sezonpizza,
    title: "4 сезона",
    text: `Бекон, Ветчина, Грибы, Курица, Лук, Маслины, Огурцы мари...`,
    cost: 630,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.chickenpizza,
    title: "EASY PEASY чикен а-ля хрен",
    text: `Курица, Лук, Соус Карбонара,...`,
    cost: 249,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.chilipizza,
    title: "Чикен Сладкий Чили",
    text: `Курица, Лук, Перец Халапеньо, Сыр Моцарелла, Томатный соу...`,
    cost: 399,
    news: true,
    xit: false,
    new: true,
  },
  {
    img: images.pizzakolbas,
    title: "EASY PEASY огуречный расколбас",
    text: `Курица, Лук, Перец Халапеньо...`,
    cost: 549,
    news: true,
    xit: true,
    new: false,
  },
];

export default pizza;
