import images from "./images";

const snacks = [
  {
    img: images.fri,
    title: "Фири",
    text: `Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...`,
    cost: 475,
    news: true,
    xit: false,
    new: true,
  },
  {
    img: images.kfc,
    title: "КФС",
    text: `Сливочный сыр, семга татаки с тростниковым сахаром, соус у...`,
    cost: 395,
    news: true,
    xit: true,
    new: false,
  },
  {
    img: images.popcorn,
    title: "Popcorn",
    text: `Действительно много семги, сливочный сыр, огурец, рис, н...`,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.lavash,
    title: "Лаваш",
    text: `Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...`,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.lavash,
    title: "Лаваш",
    text: `Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...`,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.popcorn,
    title: "Popcorn",
    text: `Действительно много семги, сливочный сыр, огурец, рис, н...`,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.chilipizza,
    title: "Фири",
    text: `Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...`,
    cost: 475,
    news: false,
    xit: false,
    new: true,
  },
  {
    img: images.chilipizza,
    title: "Филадельфия крем-брюле",
    text: `Сливочный сыр, семга татаки с тростниковым сахаром, соус у...`,
    cost: 395,
    news: false,
    xit: true,
    new: false,
  },
];

export default snacks;
