import images from "./images";

const sushi = [
  {
    img: images.sushi1,
    title: "Филадельфия кранч",
    text: `Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...`,
    cost: 475,
    news: true,
    xit: false,
    new: true,
  },
  {
    img: images.sushi2,
    title: "Филадельфия крем-брюле",
    text: `Сливочный сыр, семга татаки с тростниковым сахаром, соус у...`,
    cost: 395,
    news: true,
    xit: true,
    new: false,
  },
  {
    img: images.sushi3,
    title: "Супер Филадельфия",
    text: `Действительно много семги, сливочный сыр, огурец, рис, н...`,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.sushi4,
    title: "Тигр мама",
    text: `Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...`,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.sushi4,
    title: "Тигр мама",
    text: `Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...`,
    cost: 525,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.sushi3,
    title: "Супер Филадельфия",
    text: `Действительно много семги, сливочный сыр, огурец, рис, н...`,
    cost: 425,
    news: false,
    xit: true,
    new: false,
  },
  {
    img: images.sushi1,
    title: "Филадельфия кранч",
    text: `Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...`,
    cost: 475,
    news: false,
    xit: false,
    new: true,
  },
  {
    img: images.sushi2,
    title: "Филадельфия крем-брюле",
    text: `Сливочный сыр, семга татаки с тростниковым сахаром, соус у...`,
    cost: 395,
    news: false,
    xit: true,
    new: false,
  },
];

export default sushi;
